version: "3"

services:
  app:
    container_name: brewery_app
    restart: always
    build: ./
    ports:
      - "7070:7070"
    depends_on:
      - db
  db:
    container_name: brewery_db
    restart: always
    build: ./src/main/resources/
    expose:
      - "5432"
    volumes:
      - ./data:/data/db
    ports:
      - "5432:5432"
