test_brewery:
	source app/brewery/.env && ./gradlew :app:brewery:test

build_brewery:
	source app/brewery/.env && ./gradlew :app:brewery:build

test_customersupport:
	./gradlew :app:customersupport:test
